#!/bin/bash
sleep 1
killall -e xdg-desktop-portal-hyprland
killall xdg-desktop-portal
sleep 1
/usr/libexec/xdg-desktop-portal-hyprland &
logger 'xdg-desktop-portal-hyprland started'
sleep 2
/usr/libexec/xdg-desktop-portal &
logger 'xdg-desktop-portal started'
